export const spanishHeaders = {
    'Nombre': 'name',
    'Marca': 'brand',
    'Modelo': 'model',
    'Bien Nacional': 'nationalKey',
    'Serial': 'serial',
    'Serial Vensalud': 'key',
    'Estado del equipo': 'operative',
    'Condicion': 'condition',
    'Descripcion': 'description',
    'Fecha': 'date',
    'Tipo de Reparacion': 'TypeRepair',
    'Tipo de Hospital': 'typeCenter',
    'Director': 'director',
    'Direccion': 'address',
    'Telefono': 'phoneNumber',
    'Piso': 'floor',
    'Servicio medico': 'service',

}
